name: Lint & Test

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    remesh:
        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [14.x, 16.x, 17.x, 18.x]
                os: [ubuntu-latest, macos-latest, windows-latest]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Check out
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: '6'

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1.4.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Init
              run: pnpm run init

            - name: Build & Test
              run: pnpm run build && pnpm run test
